project_id = "ghegifxvmegfoqixbozt"

[functions.generate-embeddings]
verify_jwt = false

[functions.optimize-content]
verify_jwt = false

[functions.optimize-content-stream]
verify_jwt = false

[functions.analyze-content-queries]
verify_jwt = false

[functions.analyze-chunks-stream]
verify_jwt = false
